# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.Error" do
    optional :code, :string, 1
    optional :message, :string, 2
    optional :reference, :string, 3
    optional :error_class, :string, 4
    optional :http_code, :uint32, 5
    repeated :original, :message, 6, "work_api.protobufs.Error"
  end
end

module WorkApi
  module Protobufs
    Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.Error").msgclass
  end
end
