# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Auth" do
    optional :access_token, :string, 1
    optional :refresh_token, :string, 2
    optional :issued_at, :uint64, 3
    optional :expires_in, :uint32, 4
    optional :provider_id, :string, 5
  end
end

module WorkApi
  module Protobufs
    module Model
      Auth = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Auth").msgclass
    end
  end
end
