# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/change.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Change" do
    optional :change_type, :string, 1
    optional :detail, :string, 2
    optional :resource, :message, 3, "google.protobuf.Any"
  end
end

module WorkApi
  module Protobufs
    module Model
      Change = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Change").msgclass
    end
  end
end
