# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/contact.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.ContactGroup" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :name, :string, 3
  end
  add_message "work_api.protobufs.model.Contact" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :title, :string, 3
    optional :first_name, :string, 4
    optional :middle_name, :string, 5
    optional :last_name, :string, 6
    repeated :email_addresses, :message, 7, "work_api.protobufs.model.ContactEmailAddress"
    repeated :phone_numbers, :message, 8, "work_api.protobufs.model.ContactPhoneNumber"
    repeated :addresses, :message, 9, "work_api.protobufs.model.ContactAddress"
    repeated :groups, :message, 10, "work_api.protobufs.model.ContactGroup"
    optional :picture_url, :string, 11
    optional :created_at, :uint64, 12
    optional :updated_at, :uint64, 13
  end
  add_message "work_api.protobufs.model.ContactEmailAddress" do
    optional :primary, :bool, 1
    optional :type, :string, 2
    optional :address, :string, 3
  end
  add_message "work_api.protobufs.model.ContactPhoneNumber" do
    optional :primary, :bool, 1
    optional :type, :string, 2
    optional :number, :string, 3
  end
  add_message "work_api.protobufs.model.ContactAddress" do
    optional :primary, :bool, 1
    optional :type, :string, 2
    optional :street, :string, 3
    optional :city, :string, 4
    optional :region, :string, 5
    optional :postal_code, :string, 6
    optional :country, :string, 7
  end
end

module WorkApi
  module Protobufs
    module Model
      ContactGroup = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.ContactGroup").msgclass
      Contact = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Contact").msgclass
      ContactEmailAddress = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.ContactEmailAddress").msgclass
      ContactPhoneNumber = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.ContactPhoneNumber").msgclass
      ContactAddress = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.ContactAddress").msgclass
    end
  end
end
