# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/environment.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.ProviderConfig" do
    optional :id, :string, 1
    optional :label, :string, 2
    optional :provider_name, :string, 3
    optional :configuration, :string, 4
  end
  add_message "work_api.protobufs.model.Environment" do
    optional :id, :string, 1
    optional :guid, :string, 2
    repeated :provider_configs, :message, 3, "work_api.protobufs.model.ProviderConfig"
    optional :public_key, :string, 4
    optional :private_key, :string, 5
    optional :api_user_count, :int32, 6
  end
end

module WorkApi
  module Protobufs
    module Model
      ProviderConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.ProviderConfig").msgclass
      Environment = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Environment").msgclass
    end
  end
end
