# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/event.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'protobufs/model/email_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Calendar" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :name, :string, 3
    optional :description, :string, 4
    optional :location, :string, 5
    optional :time_zone, :string, 6
  end
  add_message "work_api.protobufs.model.EventReminder" do
    optional :reminder_method, :string, 1
    optional :description, :string, 2
    optional :summary, :string, 3
    optional :minutes_before, :uint64, 4
  end
  add_message "work_api.protobufs.model.Event" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :name, :string, 3
    optional :description, :string, 4
    repeated :attendees, :message, 5, "work_api.protobufs.model.EventAttendee"
    optional :start_date_time, :string, 6
    optional :start_timezone, :string, 7
    optional :end_date_time, :string, 8
    optional :end_timezone, :string, 9
    optional :location, :string, 10
    optional :all_day, :bool, 11
    repeated :reminders, :message, 12, "work_api.protobufs.model.EventReminder"
    optional :recurrence, :string, 13
    optional :parent_event_id, :string, 14
    repeated :attachments, :message, 15, "work_api.protobufs.model.EventAttachment"
    optional :created_at, :uint64, 16
    optional :updated_at, :uint64, 17
    optional :calendar_id, :string, 18
  end
  add_message "work_api.protobufs.model.EventAttachment" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :payload, :message, 3, "google.protobuf.Any"
  end
  add_message "work_api.protobufs.model.EventAttendee" do
    optional :profile_id, :string, 1
    optional :email_address, :string, 2
    optional :display_name, :string, 3
    optional :organizer, :bool, 4
    optional :self, :bool, 5
    optional :resource, :bool, 6
    optional :optional, :bool, 7
    optional :response_status, :string, 8
    optional :comment, :string, 9
    optional :additional_guests, :uint32, 10
    optional :integration_id, :string, 11
  end
end

module WorkApi
  module Protobufs
    module Model
      Calendar = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Calendar").msgclass
      EventReminder = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.EventReminder").msgclass
      Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Event").msgclass
      EventAttachment = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.EventAttachment").msgclass
      EventAttendee = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.EventAttendee").msgclass
    end
  end
end
