# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/file.proto

require 'google/protobuf'

require 'protobufs/model/parent_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.File" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :filename, :string, 3
    repeated :parents, :message, 4, "work_api.protobufs.model.Parent"
    optional :size, :uint64, 5
    optional :mime_type, :string, 6
    optional :last_modified_at, :uint64, 7
    optional :storage_ref, :message, 8, "work_api.protobufs.model.StorageRef"
    optional :data, :bytes, 9
    optional :created_at, :uint64, 10
    optional :extension, :string, 11
    optional :kind, :string, 12
    optional :remote_url, :string, 13
    repeated :permissions, :message, 14, "work_api.protobufs.model.FilePermission"
  end
  add_message "work_api.protobufs.model.StorageRef" do
    optional :path, :string, 1
    optional :uri, :string, 2
    optional :expires_at, :uint64, 3
  end
  add_message "work_api.protobufs.model.SharedPermissionDetail" do
    optional :type, :enum, 1, "work_api.protobufs.model.SharedPermissionType"
    optional :primary_role, :enum, 2, "work_api.protobufs.model.PermissionRole"
    optional :inherited_id, :string, 3
  end
  add_message "work_api.protobufs.model.FilePermission" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :type, :enum, 3, "work_api.protobufs.model.PermissionType"
    repeated :roles, :enum, 4, "work_api.protobufs.model.PermissionRole"
    optional :display_name, :string, 5
    optional :email_address, :string, 6
    optional :domain, :string, 7
    optional :expiry, :uint64, 8
    optional :discoverable, :enum, 9, "work_api.protobufs.model.PermissionDiscoverable"
    optional :permission_detail, :message, 10, "work_api.protobufs.model.SharedPermissionDetail"
  end
  add_enum "work_api.protobufs.model.PermissionDiscoverable" do
    value :FALSE, 0
    value :TRUE, 1
    value :NOT_APPLICABLE, 2
  end
  add_enum "work_api.protobufs.model.PermissionRole" do
    value :OWNER, 0
    value :ORGANIZER, 1
    value :FILE_ORGANIZER, 2
    value :WRITER, 3
    value :COMMENTER, 4
    value :READER, 5
    value :MEMBER, 6
  end
  add_enum "work_api.protobufs.model.PermissionType" do
    value :USER, 0
    value :GROUP, 1
    value :DOMAIN, 2
    value :ANYONE, 3
  end
  add_enum "work_api.protobufs.model.SharedPermissionType" do
    value :SHARED_FILE, 0
    value :SHARED_MEMBER, 1
  end
end

module WorkApi
  module Protobufs
    module Model
      File = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.File").msgclass
      StorageRef = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.StorageRef").msgclass
      SharedPermissionDetail = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.SharedPermissionDetail").msgclass
      FilePermission = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.FilePermission").msgclass
      PermissionDiscoverable = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.PermissionDiscoverable").enummodule
      PermissionRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.PermissionRole").enummodule
      PermissionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.PermissionType").enummodule
      SharedPermissionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.SharedPermissionType").enummodule
    end
  end
end
