# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/integration.proto

require 'google/protobuf'

require 'protobufs/model/auth_pb'
require 'protobufs/model/subscription_pb'
require 'protobufs/model/environment_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Integration" do
    optional :id, :string, 1
    optional :provider, :string, 2
    optional :media_type, :string, 4
    optional :auth, :message, 5, "work_api.protobufs.model.Auth"
    repeated :subscriptions, :message, 6, "work_api.protobufs.model.Subscription"
    optional :environment, :message, 7, "work_api.protobufs.model.Environment"
    optional :created_at, :uint64, 8
    optional :provider_id, :string, 9
  end
end

module WorkApi
  module Protobufs
    module Model
      Integration = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Integration").msgclass
    end
  end
end
