# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/parent.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Parent" do
    optional :remote_id, :string, 1
    optional :integration_id, :string, 2
    optional :type, :string, 3
    optional :model, :message, 4, "google.protobuf.Any"
  end
end

module WorkApi
  module Protobufs
    module Model
      Parent = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Parent").msgclass
    end
  end
end
