# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/subscription.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Subscription" do
    optional :remote_id, :string, 1
    optional :expiry_time, :uint64, 2
    optional :sync_token, :string, 3
  end
end

module WorkApi
  module Protobufs
    module Model
      Subscription = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Subscription").msgclass
    end
  end
end
