# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/usage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.Usage" do
    optional :id, :string, 1
    optional :started_at, :uint64, 2
    optional :finished_at, :uint64, 3
    optional :data, :string, 4
    optional :updated_at, :uint64, 5
  end
end

module WorkApi
  module Protobufs
    module Model
      Usage = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.Usage").msgclass
    end
  end
end
