# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/model/user.proto

require 'google/protobuf'

require 'protobufs/model/integration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "work_api.protobufs.model.User" do
    optional :id, :string, 1
    optional :arbitrary_id, :string, 2
    optional :created_at, :uint64, 4
    optional :token, :string, 5
    repeated :integrations, :message, 6, "work_api.protobufs.model.Integration"
    optional :environment_guid, :string, 7
  end
end

module WorkApi
  module Protobufs
    module Model
      User = Google::Protobuf::DescriptorPool.generated_pool.lookup("work_api.protobufs.model.User").msgclass
    end
  end
end
