---
http_interactions:
- request:
    method: post
    uri: https://api-alpha.work-api.com/integrations
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"provider":"gcal","media_type":"event"},"type":"integration"}}'
    headers:
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODQwMDYyMTcsImlhdCI6MTU4MTU4NzAxNywiaXNzIjoiU1BJQ08gQWNjb3VudCIsInVzZXIiOnsiaWQiOiI1ZTQ0MjQ4YmM0YzQzZDAwMTY4MTQ4MmQiLCJhcmJpdHJhcnlfaWQiOiJ0ZXN0MjU5NzkwN0B3b3JrLWFwaS5jb20ifX0.OCSYExauEyQGvMPWQLTJlA9hzhzVRbrF-TyolrwSpWE
      Accept:
      - application/vnd.api+json
      User-Agent:
      - Faraday v0.15.4
      Content-Type:
      - application/vnd.api+json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 201
      message: Created
    headers:
      Server:
      - Cowboy
      Connection:
      - keep-alive
      Date:
      - Mon, 17 Feb 2020 13:00:01 GMT
      X-Request-Id:
      - 60f1031a-8375-4aeb-8758-1b07ee8df584
      Content-Type:
      - application/vnd.api+json
      Content-Length:
      - '136'
      Vary:
      - Origin
      Via:
      - 1.1 vegur
    body:
      encoding: UTF-8
      string: '{"data":{"id":"5e4a8e515a83120022901da6","type":"integration","attributes":{"provider":"gcal","provider_id":null,"media_type":"event"}}}'
    http_version: null
  recorded_at: Mon, 17 Feb 2020 13:00:01 GMT
- request:
    method: get
    uri: https://api-alpha.work-api.com/auth/init/5e4a8e515a83120022901da6?integration_id=5e4a8e515a83120022901da6&redirect=false&return_to=http://localhost:3000/done
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODQwMDYyMTcsImlhdCI6MTU4MTU4NzAxNywiaXNzIjoiU1BJQ08gQWNjb3VudCIsInVzZXIiOnsiaWQiOiI1ZTQ0MjQ4YmM0YzQzZDAwMTY4MTQ4MmQiLCJhcmJpdHJhcnlfaWQiOiJ0ZXN0MjU5NzkwN0B3b3JrLWFwaS5jb20ifX0.OCSYExauEyQGvMPWQLTJlA9hzhzVRbrF-TyolrwSpWE
      Accept:
      - application/vnd.api+json
      User-Agent:
      - Faraday v0.15.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Server:
      - Cowboy
      Connection:
      - keep-alive
      Date:
      - Mon, 17 Feb 2020 13:00:10 GMT
      Content-Type:
      - application/vnd.api+json
      Content-Length:
      - '125'
      Vary:
      - Origin
      Via:
      - 1.1 vegur
    body:
      encoding: UTF-8
      string: '{"errors":[{"code":"remote_authorization_missing_error","detail":"credentials
        for underlying API have not been provided: "}]}'
    http_version: null
  recorded_at: Mon, 17 Feb 2020 13:00:10 GMT
- request:
    method: get
    uri: https://api-alpha.work-api.com/auth/init/5e4a8e515a83120022901da6?integration_id=5e4a8e515a83120022901da6&redirect=true&return_to=http://localhost:3000/done
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODU1NjA3MDgsImlhdCI6MTU4MzE0MTUwOCwiaXNzIjoiU1BJQ08gQWNjb3VudCIsInVzZXIiOnsiaWQiOiI1ZTRhYmQzYjJjMjgwYTAwMWUzMjFkODgiLCJhcmJpdHJhcnlfaWQiOiJ0ZXN0NDc1NDk5MEB3b3JrLWFwaS5jb20ifX0.s2O_M_-QMo3Qi3khEcENEeMJFU23gdRiCNb5cTHWhIU
      Accept:
      - application/vnd.api+json
      User-Agent:
      - Faraday v0.15.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Server:
      - Cowboy
      Date:
      - Mon, 02 Mar 2020 13:36:26 GMT
      Connection:
      - close
      Via:
      - 1.1 vegur
    body:
      encoding: UTF-8
      string: ''
    http_version: null
  recorded_at: Mon, 02 Mar 2020 13:36:27 GMT
- request:
    method: get
    uri: https://api-alpha.work-api.com/auth/init/5e4a8e515a83120022901da6?redirect=false&return_to=http://localhost:3000/done
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODU1NjA3MDgsImlhdCI6MTU4MzE0MTUwOCwiaXNzIjoiU1BJQ08gQWNjb3VudCIsInVzZXIiOnsiaWQiOiI1ZTRhYmQzYjJjMjgwYTAwMWUzMjFkODgiLCJhcmJpdHJhcnlfaWQiOiJ0ZXN0NDc1NDk5MEB3b3JrLWFwaS5jb20ifX0.s2O_M_-QMo3Qi3khEcENEeMJFU23gdRiCNb5cTHWhIU
      Accept:
      - application/vnd.api+json
      User-Agent:
      - Faraday v0.15.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Server:
      - Cowboy
      Date:
      - Mon, 02 Mar 2020 14:31:44 GMT
      Connection:
      - close
      Via:
      - 1.1 vegur
    body:
      encoding: UTF-8
      string: ''
    http_version: null
  recorded_at: Mon, 02 Mar 2020 14:31:45 GMT
recorded_with: VCR 5.1.0
