# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("model/auth.proto", :syntax => :proto3) do
    add_message "livil.model.Auth" do
      optional :access_token, :string, 1
      optional :refresh_token, :string, 2
      optional :issued_at, :uint64, 3
      optional :expires_in, :uint32, 4
      optional :provider_id, :string, 5
    end
  end
end

module Livil
  module Model
    Auth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livil.model.Auth").msgclass
  end
end
