# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/change.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('model/change.proto', syntax: :proto3) do
    add_message 'livil.model.Change' do
      optional :change_type, :string, 1
      optional :detail, :string, 2
      optional :resource, :message, 3, 'google.protobuf.Any'
    end
  end
end

module Livil
  module Model
    Change = Google::Protobuf::DescriptorPool.generated_pool.lookup('livil.model.Change').msgclass
  end
end
