# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/environment.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("model/environment.proto", :syntax => :proto3) do
    add_message "livil.model.ProviderConfig" do
      optional :id, :string, 1
      optional :label, :string, 2
      optional :provider_name, :string, 3
      optional :configuration, :string, 4
    end
    add_message "livil.model.Environment" do
      optional :id, :string, 1
      optional :guid, :string, 2
      repeated :provider_configs, :message, 3, "livil.model.ProviderConfig"
      optional :public_key, :string, 4
      optional :private_key, :string, 5
      optional :api_user_count, :int32, 6
    end
  end
end

module Livil
  module Model
    ProviderConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livil.model.ProviderConfig").msgclass
    Environment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livil.model.Environment").msgclass
  end
end
