# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/integration.proto

require 'google/protobuf'

require_relative './auth_pb'
require_relative './subscription_pb'
require_relative './environment_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('model/integration.proto', syntax: :proto3) do
    add_message 'livil.model.Integration' do
      optional :id, :string, 1
      optional :provider, :string, 2
      optional :media_type, :string, 4
      optional :auth, :message, 5, 'livil.model.Auth'
      repeated :subscriptions, :message, 6, 'livil.model.Subscription'
      optional :environment, :message, 7, 'livil.model.Environment'
      optional :created_at, :uint64, 8
    end
  end
end

module Livil
  module Model
    Integration = Google::Protobuf::DescriptorPool.generated_pool.lookup('livil.model.Integration').msgclass
  end
end
