# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/parent.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("model/parent.proto", :syntax => :proto3) do
    add_message "livil.model.Parent" do
      optional :remote_id, :string, 1
      optional :integration_id, :string, 2
      optional :type, :string, 3
      optional :model, :message, 4, "google.protobuf.Any"
    end
  end
end

module Livil
  module Model
    Parent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livil.model.Parent").msgclass
  end
end
