# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/resource.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('model/resource.proto', syntax: :proto3) do
    add_message 'livil.model.Resource' do
      optional :remote_id, :string, 1
      optional :integration_id, :string, 2
    end
  end
end

module Livil
  module Model
    Resource = Google::Protobuf::DescriptorPool.generated_pool.lookup('livil.model.Resource').msgclass
  end
end
