# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/search.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("model/search.proto", :syntax => :proto3) do
  end
end

